---
abstract: 'Read and write config as a YAML data structure'
author:
  - 'Dominique Dumont'
build_requires:
  Config::Model::Tester: '4.001'
  Config::Model::Tester::Setup: '0'
  ExtUtils::testlib: '0'
  Module::Build: '0.34'
  Path::Tiny: '0'
  Test::Memory::Cycle: '0'
  Test::More: '0'
  lib: '0'
  utf8: '0'
configure_requires:
  Module::Build: '0.34'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Model-Backend-Yaml
requires:
  Carp: '0'
  Config::Model: '2.131'
  Config::Model::Backend::Any: '0'
  Config::Model::Exception: '0'
  File::Path: '0'
  Log::Log4perl: '0'
  YAML::XS: '0.69'
  base: '0'
  boolean: '0'
  parent: '0'
  perl: v5.12.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dod38fr/config-model-backend-yaml/issues
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model-backend-yaml.git
version: '2.134'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: LGPL-2.1
